sources:
  - ingress

provider: aws

aws:
  secretKey: OVERRIDEME
  accessKey: OVERRIDEME

txtOwnerId: "k8s"

policy: upsert-only

rbac:
  create: true

podAnnotations:
  "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
