apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nginx-ingress-default-backend
  namespace: kube-system
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: nginx-ingress
      component: default-backend
