kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  namespace: kube-system
data:
  use-proxy-protocol: "true"
  proxy-body-size: "8m"
